### ISSUE TITLE
script to show info in lcd

### ISSUE THREAD

**Issue by nickiman** [xyb/lcd2usb#3]
Hi,
I´m using your SW combined with RPI-Monitor to read the data from a sensor and place it in my lcd.
I´ve bought this lcd http://www.lcdmodkit.com/lcd/U204FR-A2.html which is compatible with lcd2usb.

The script that I´m using is this:

```#!/usr/bin/env python
import httplib, time, os, sys, json
from lcd2usb import LCD
lcd = LCD()

# class Process dedicated to process data get from Client
# and send information to LCD and console
class Process:
  # Process constructor
  def run(self, jsonString):
    # Parse data as json
    data = json.loads( jsonString )
    # Try to get data from json or return default value
    try:
      rpi_temperature = data['living_room_temp']
    except:
      rpi_temperature = "--.---"
    try:
      rpi_humidity = data['humidity']
    except:
      rpi_humidity = "--.--"
    # Construct string to be displayed on screens
    temperature= "Temperatura: %s C" % rpi_temperature
    humidity= "Humedad:     %s %%" % rpi_humidity
    lcd.clear()
    lcd.write('Sensor RPi-Monitor', 0, 0)
    lcd.write('temperature', 0, 2)
    lcd.write('humidity', 0, 3)
    # Also print string in console
    os.system("clear")
    print " RPi-Monitor "
    print
    print temperature
    print humidity
    print
    time.sleep(1)

# Class client design to work as web client and get information 
# from RPi-Monitor embedded web server
class Client:
  # Client constructor
  def __init__(self):
    # Create a Process object
    self.process = Process()

  def run(self):
    # Infinite loop
    while True:
     try:
       # Initiate a connection to RPi-Monitor embedded server
       connection = httplib.HTTPConnection("localhost", 8888)
       # Get the file dynamic.json
       connection.request("GET","/dynamic.json")
       # Get the server response
       response = connection.getresponse()
       if ( response.status == 200 ):
         # If response is OK, read data
         data = response.read()
         # Run process object on extracted data
         self.process.run(data)
       # Close the connection to RPi-Monitor embedded server
       connection.close()
     finally:
       # Wait 5 secondes before restarting the loop
       time.sleep(5)

# Main function
def main():
  try:
    # Create a Client object
    client = Client()
    # Run it
    client.run()
  except KeyboardInterrupt:
    # if Ctrl+C has been pressed
    # turn off the lcd backlight
    lcd.backlight(0); 
    # exit from the program 
    sys.exit(0)

# Execute main if the script is directly called
if __name__ == "__main__":
    main()
```

I can check that the part of the web client to get the information from web server is OK because I can see printed in console this:

>  RPi-Monitor
> 
> Temperatura: 26.9 C
> Humedad:     33.4 %

But in the lcd I only get this lines:

> Sensor RPI-Monitor
> 
> temperature
> humidity

I should expect the same lines "Temperatura" and "Humedad" with your values as in console to be showed in the lcd... but it doesn´t work.

Could you help me please?

**Comment by xyb** [comment]
Hi, you may want to change these lines to:

    # Construct string to be displayed on screens
    temperature= "Temperatura: %s C" % rpi_temperature
    humidity= "Humedad:     %s %%" % rpi_humidity
    lcd.clear()
    lcd.write('Sensor RPi-Monitor', 0, 0)
    lcd.write(temperature, 0, 2)
    lcd.write(humidity, 0, 3)

let lcd display the `temperature` and `humidity` variables than the strings itself.

**Comment by nickiman** [comment]
Hi,
problem is that if I write that lines as you suggest me I get this error:

> Traceback (most recent call last):
  File "./lcd_info.py", line 83, in <module>
    main()
  File "./lcd_info.py", line 73, in main
    client.run()
  File "./lcd_info.py", line 60, in run
    self.process.run(data)
  File "./lcd_info.py", line 27, in run
    lcd.write(temperature, 0, 2)
  File "/usr/local/lib/python2.7/dist-packages/lcd2usb.py", line 271, in write
    self._enqueue(LCD_DATA | ctrl, char)
  File "/usr/local/lib/python2.7/dist-packages/lcd2usb.py", line 217, in _enqueue
    self.buffer[self.buffer_current_fill] = value
TypeError: an integer or string of size 1 is required

And I don´t know how to proceed. So your help will be really appreciated.
Regards

**Comment by xyb** [comment]
Did you run this with python 3? This library is developed with python 2 only. Please modify these lines:

    lcd.write(temperature, 0, 2)
    lcd.write(humidity, 0, 3)

to:

    lcd.write(str.encode(temperature), 0, 2)
    lcd.write(str.encode(humidity), 0, 3)

these code is compatible with 3, hopefully. I will release a new version for python 2 and 3 if this solution is ok.

**Comment by nickiman** [comment]
Hi,
Sorry for the delay to answer you. I´m running python 2 specifically this version:

`root@weatherstation:/# python --version
Python 2.7.9
`
Changing the script as you suggested. I get this output:

```
Traceback (most recent call last):
  File "./lcd_info.py", line 83, in <module>
    main()
  File "./lcd_info.py", line 73, in main
    client.run()
  File "./lcd_info.py", line 60, in run
    self.process.run(data)
  File "./lcd_info.py", line 27, in run
    lcd.write(str.encode(temperature), 0, 2)
TypeError: descriptor 'encode' requires a 'str' object but received a 'unicode'

```
Anyway I´ve been writing in a python forum about my issue and a user advised me to write these lines:

 ```temperature = temperature.encode()
    humidity = humidity.encode()
    lcd.clear()
    lcd.write('Sensor RPi-Monitor', 0, 0)
    lcd.write(temperature, 0, 2)
    lcd.write(humidity, 0, 3)
```
And it works... but if you consider another way... I´m willing to try it and tell you if it works also or not.
Thank you very much.
Nicolas

**Comment by xyb** [comment]
Good to know this, thank you 😄
