### ISSUE TITLE
big characters

### ISSUE THREAD

**Issue by nickiman** [xyb/lcd2usb#4]
Hi,
is there any way to show big characters in the lcd? and different symbols? Something like this:
![imagen](https://cloud.githubusercontent.com/assets/3627902/21117182/ef7d7c28-c0b8-11e6-8126-246cfeb0358b.png)

Or this one:
![imagen](https://cloud.githubusercontent.com/assets/3627902/21117346/74cab2a6-c0b9-11e6-9301-19c83e0c2d6a.png)

And for write symbols like this?:
![imagen](https://cloud.githubusercontent.com/assets/3627902/21117378/9ed6a942-c0b9-11e6-842b-56a35374133b.png)

Thank you very much for your support!!

**Comment by xyb** [comment]
Hi, @nickiman, sure, you can define symbols if you want. You may want to check the [lcd2usb.py](https://github.com/xyb/lcd2usb/blob/master/lcd2usb.py#L307-L309) and [examples/blink.py](https://github.com/xyb/lcd2usb/blob/master/examples/blink.py) for demonstrates.

**Comment by nickiman** [comment]
Could you tell me how do you convert the symbols in byte array? 
I´ve seen some programs in the web but not sure that are what I need.
By the way, it could be also possible create big characters?
Sorry for the noob questions I´m starting to use LCDs with python.
Thank you very much.

**Comment by xyb** [comment]
@nickiman, [my favorite tool](http://www.quinapalus.com/hd44780udg.html) is designed by quinapalus.com. I have mentioned it in [lcd2usb.py](https://github.com/xyb/lcd2usb/blob/master/lcd2usb.py#L290), maybe I should recommend it in README file :)
