### ISSUE TITLE
在windows环境下from usb2lcd import LCD时报错

### ISSUE THREAD

**Issue by 30344386** [xyb/lcd2usb#6]
exceptions.WindowsError
[Error 126] 
开发环境使用的python2.7
不知是否我哪里操作不到位？
已经安装了
lcd2usb                      1.2
libusb                         1.0.22b4
libusb1                       1.7

**Comment by xyb** [comment]
@30344386 看起来是 windows 找 DLL 时出现了问题，你可以把相关动态库文件都放到当前目录试试。参见 https://stackoverflow.com/a/25492172

**Comment by 30344386** [comment]
谢谢您的回复！今日一直期待您的答复！感谢您对我的问题给于解答！
